SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE DeliveryProcessDefinition;
TRUNCATE TABLE Activity;
TRUNCATE TABLE Context;
TRUNCATE TABLE OutcomeDefinition;
TRUNCATE TABLE ProjectPlan;
TRUNCATE TABLE MilestoneDefinition;
TRUNCATE TABLE RoleDefinition;
TRUNCATE TABLE WorkProductDefinition;
TRUNCATE TABLE TaskDefinition;
TRUNCATE TABLE WorkstreamDefinition;
TRUNCATE TABLE DeliverableDefinition;
TRUNCATE TABLE GuidanceDefinition;
TRUNCATE TABLE GuidanceToGuidance;
TRUNCATE TABLE RoleToGuidance;
TRUNCATE TABLE TaskToRole;
TRUNCATE TABLE TaskToWorkProduct;
TRUNCATE TABLE TaskToGuidance;
TRUNCATE TABLE WorkstreamToTask;
TRUNCATE TABLE TaskUsage;
TRUNCATE TABLE WBS;
TRUNCATE TABLE WorkProductToGuidance;
TRUNCATE TABLE DeliverableParts;
TRUNCATE TABLE GettingStarted;
TRUNCATE TABLE PursuitSupport;
TRUNCATE TABLE PlanAttachments;
TRUNCATE TABLE ReleaseInformation;
TRUNCATE TABLE Predecessor;
TRUNCATE TABLE ProcessToGuidance;
TRUNCATE TABLE StepDefinition;
TRUNCATE TABLE TaskToStep;
TRUNCATE TABLE TeamDefinition;
TRUNCATE TABLE TeamToTask;
TRUNCATE TABLE WorkProductToWorkProduct;
SET FOREIGN_KEY_CHECKS = 1;

